/**:
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1
        y: 0
      scale_linear:
        x: -0.4
        y: -0.4
      axis_angular:
        yaw: 2
      scale_angular:
        yaw: -0.5
      require_enable_button: false
      shoot_button: 1
      enable_turbo_button: 8
