/**:
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1
        y: 0
      scale_linear:
        x: -1.8
        y: -1.8
      axis_angular:
        yaw: 2
      scale_angular:
        yaw: -3.0
      require_enable_button: false
      shoot_button: 5
      enable_turbo_button: 8
